[project]
name = "nekt-target-hubspot"
version = "0.0.1"
description = "`target-hubspot` is a Singer target for HubSpot, built with the Meltano Singer SDK."
readme = "README.md"
authors = [{ name = "Pat Nadolny" }]
license = "Apache-2.0"
keywords = [
    "ELT",
    "HubSpot",
]
requires-python = "<3.12,>=3.11"
dependencies = [
    "fs-s3fs>=1.1.1",
    "hubspot-api-client>=8.0.0",
    "nekt-singer-sdk @ git+https://github.com/nektcom/singer-sdk.git@v0.24.0",
    "requests>=2.31.0",
    "setuptools>=80.9.0",
]

[project.optional-dependencies]
s3 = [
    "fs-s3fs",
]

[project.scripts]
target-hubspot = 'target_hubspot.target:TargetHubSpot.cli'

[dependency-groups]
dev = [
    "pytest>=7.2.1",
]

[tool.hatch.build.targets.wheel]
packages = [
    "target_hubspot",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.ruff]
ignore = [
    "ANN101",  # missing-type-self
    "ANN102",  # missing-type-cls
]
select = ["ALL"]
src = ["target_hubspot"]
target-version = "py37"

[tool.ruff.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.isort]
known-first-party = ["target_hubspot"]

[tool.ruff.pydocstyle]
convention = "google"


[build-system]
requires = ["hatchling>=1,<2"]
build-backend = "hatchling.build"
